export default [
    {
        note: 'c4',
        noteWithoutOctave: 'c',
        accidental: false,
        keyboardBinding: 'Z',
    },
    {
        note: 'c#4',
        noteWithoutOctave: 'c',
        accidental: true,
        keyboardBinding: 'S',
    },	
    {
        note: 'd4',
        noteWithoutOctave: 'd',
        accidental: false,
        keyboardBinding: 'X',
    },
    {
        note: 'd#4',
        noteWithoutOctave: 'd',
        accidental: true,
        keyboardBinding: 'D',
    },
    {
        note: 'e4',
        noteWithoutOctave: 'e',
        accidental: false,
        keyboardBinding: 'C',
    },
    {
        note: 'f4',
        noteWithoutOctave: 'f',
        accidental: false,
        keyboardBinding: 'V',
    },
    {
        note: 'f#4',
        noteWithoutOctave: 'f',
        accidental: true,
        keyboardBinding: 'G',
    },
    {
        note: 'g4',
        noteWithoutOctave: 'g',
        accidental: false,
        keyboardBinding: 'B',
    },
    {
        note: 'g#4',
        noteWithoutOctave: 'g',
        accidental: true,
        keyboardBinding: 'H',
    },
    {
        note: 'a4',
        noteWithoutOctave: 'a',
        accidental: false,
        keyboardBinding: 'N',
    },
    {
        note: 'a#4',
        noteWithoutOctave: 'a',
        accidental: true,
        keyboardBinding: 'J',
    },
    {
        note: 'b4',
        noteWithoutOctave: 'b',
        accidental: false,
        keyboardBinding: 'M',
    },
    {
        note: 'c5',
        noteWithoutOctave: 'c',
        accidental: false,
        keyboardBinding: 'Q',
    },
    {
        note: 'c#5',
        noteWithoutOctave: 'c',
        accidental: true,
        keyboardBinding: '2',
    },	
    {
        note: 'd5',
        noteWithoutOctave: 'd',
        accidental: false,
        keyboardBinding: 'W',
    },
    {
        note: 'd#5',
        noteWithoutOctave: 'd',
        accidental: true,
        keyboardBinding: '3',
    },
    {
        note: 'e5',
        noteWithoutOctave: 'e',
        accidental: false,
        keyboardBinding: 'E',
    },
    {
        note: 'f5',
        noteWithoutOctave: 'f',
        accidental: false,
        keyboardBinding: 'R',
    },
    {
        note: 'f#5',
        noteWithoutOctave: 'f',
        accidental: true,
        keyboardBinding: '5',
    },
    {
        note: 'g5',
        noteWithoutOctave: 'g',
        accidental: false,
        keyboardBinding: 'T',
    },
    {
        note: 'g#5',
        noteWithoutOctave: 'g',
        accidental: true,
        keyboardBinding: '6',
    },
    {
        note: 'a5',
        noteWithoutOctave: 'a',
        accidental: false,
        keyboardBinding: 'Y',
    },
    {
        note: 'a#5',
        noteWithoutOctave: 'a',
        accidental: true,
        keyboardBinding: '7',
    },
    {
        note: 'b5',
        noteWithoutOctave: 'b',
        accidental: false,
        keyboardBinding: 'U',
    },
];